### ISSUE TITLE
Sqelf container not creating network anymore

### ISSUE THREAD

**Issue by devployment** [datalust/sqelf#31]
I have used `datalust/sqelf:1.0.57.0` several days ago for testing log transfer from PHP services to Seq. Everything worked fine, after some tweaking.

Here is my seq/sqelf related docker-compose section

```
version: '2'

services:

    sqelf:
      image: datalust/sqelf:1.0.57.0
      depends_on:
        - seq
      ports:
        - "12201:12201/udp"
      environment:
        SEQ_ADDRESS: "http://seq:5341"
      restart: unless-stopped
      networks:
        - seqnet
    seq:
      image: datalust/seq:latest
      ports:
        - "5341:80"
      environment:
        ACCEPT_EULA: Y
      restart: unless-stopped
      volumes:
        - ../data/seq:/data
      networks:
        - seqnet
```

I created a separated network to prevent port collisions with other running containers

```
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
  seqnet:
    driver: "bridge"
```

Everything starts up and runs as expected. I can use PHP logging (Monolog) and configure it to send Gelf messages to sqelf, from containers that joined the same network. 

If I switch to `datalust/sqelf:1.0.118`, the sqelf container does not get a network link anymore. It joins the network and enters a restart loop. Nothing can be send to sqelf as one might expect with no network available.

All I see in the container log is a bunch of those entries

```
{"@t":"2019-02-01T19:29:49.952835500Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T19:29:54.201928200Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T19:30:01.594420500Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T19:30:15.282527100Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T19:30:41.795996400Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T19:31:33.897595400Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T19:32:34.840344600Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T19:33:35.848725100Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T19:55:10.428170700Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T19:56:11.375723600Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T19:57:12.274970500Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T19:58:13.233399700Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T19:59:14.096769Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T20:00:15.041764700Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T20:01:15.949245Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
{"@t":"2019-02-01T20:02:16.783862200Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
```

It seems not be related to my network config, as the same happens if I just start seq / sqelf without my custom config using the `dokcer-compose.yml` shown here. 

```
dc -p seq up
Creating seq_seq_1 ... done
Creating seq_sqelf_1 ... done
Attaching to seq_seq_1, seq_sqelf_1
sqelf_1  | {"@t":"2019-02-01T20:12:40.171856300Z","@l":"DEBUG","@mt":"Termination signal received; shutting down"}
seq_1    | ────────────────────────────────────────
seq_1    |   Seq ♦ Machine data, for humans.
seq_1    | ─────────── © 2019 Datalust Pty Ltd ────
seq_1    |
seq_1    | Running as server; press Ctrl+C to exit.
seq_1    |
seq_1    | [20:12:41 INF] Seq "5.0.2562" running on OS "Linux 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018"
seq_1    | [20:12:41 INF] Seq listening on ["http://localhost/", "http://localhost:5341/"]
seq_1    | [20:12:41 INF] Opening document store "/data/Documents/documents.lmdb"
seq_1    | [20:12:42 INF] Opening event store at "/data/Extents"
seq_1    | [20:12:42 INF] Available storage engines in order of preference are ["FLARE"]
seq_1    | [20:12:42 INF] Storage subsystem available
seq_sqelf_1 exited with code 0
seq_sqelf_1 exited with code 0
seq_sqelf_1 exited with code 0
seq_sqelf_1 exited with code 0
...
```

Any idea what causes this? Currently I'm a bit clueless.
