### ISSUE TITLE
High CPU usage with v2.x and TCP

### ISSUE THREAD

**Issue by dabide** [datalust/sqelf#58]
A `sqelf` container (`datalust/sqelf-ci:1.0.228-dev`) barely uses CPU. When upgraded to `datalust/sqelf:latest`, and also the 2.x CI builds, it runs at 100% on one core. This is only the case when using TCP.

```yaml
version: '3'

services:
  sqelf:
    image: datalust/sqelf-ci:1.0.228-dev
    # image: datalust/sqelf
    depends_on:
      - seq
    environment:
      SEQ_ADDRESS: "http://seq:5341"
      GELF_ADDRESS: "tcp://0.0.0.0:12201"
    restart: unless-stopped
    networks:
      - seq
    ports:
      - "12201:12201/tcp"

  seq:
    image: datalust/seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
    volumes:
    - data:/data
    ports:
      - "30080:80"
    networks:
      - seq
```

**Comment by KodrAus** [comment]
Hi @dabide! :wave:

Thanks for reaching out. I think I've been able to repro this locally so will do some digging and post back with some more details.

**Comment by KodrAus** [comment]
Hey @dabide 

We’ve got a new container available as `sqelf-ci: 2.0.260-dev` that fixes an issue with the tcp implementation where the decoder incorrectly reports its progress parsing messages back to `tokio` and will be polled continuously. Let me know if you get a chance to give that build a try!

**Comment by KodrAus** [comment]
Alrighty, I've done some testing of this new image and it appears to have sorted the issue with high CPU usage.

It's published as [`datalust/sqelf:2.0.270`](https://hub.docker.com/layers/datalust/sqelf/2.0.270/images/sha256-af875fcea2c9959d3ac3f0007220c5748830a24ee29fc9ca03933493f96d01f9) and `datalust/sqelf:latest`.

I'll go ahead and close this one now, but please feel free to re-open or file new issues if you run into anything @dabide!

**Comment by dabide** [comment]
Thanks for the fast response, @KodrAus ! I've switched to UDP, and haven't had the time to test.

**Comment by baumheld** [comment]
This issue is closed since 4 years, but I'm having the same problem. 

On production server and locally when testing with Docker Desktop: After some time the memory accumulates to 300-400 MB RAM. 
<img width="817" alt="image" src="https://github.com/datalust/seq-input-gelf/assets/141740877/0c3f6e5a-e3ff-4003-a721-a1f404913db1">

I'm using TCP with non-blocking mode. 
(UDP had the same problem as [described in another issue](https://github.com/datalust/seq-input-gelf/issues/43))

```
version: "3.9"

x-deploy: &hardware-limits
  resources:
    limits:
      memory: 2G

volumes:
  seq:

services:
  seq:
    container_name: seq
    image: datalust/seq:2023.4
    deploy: *hardware-limits
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: seqsvr/Client/seqcli node health -s http://127.0.0.1/
      timeout: 5s
      start_period: 30s
      interval: 5s
      retries: 10
    ports:
      - "5341:5341"
    environment:
      TZ: Europe/Berlin
      ACCEPT_EULA: Y
    volumes:
      - seq:/data

  seq-gelf-monitor:
    container_name: seq-gelf-monitor
    image: datalust/seq-input-gelf:3.0
    deploy: *hardware-limits
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      seq:
        condition: service_healthy
    stop_grace_period: 1s
    ports:
      - "127.0.0.1:12202:12201"
    environment:
      TZ: Europe/Berlin
      GELF_ADDRESS: tcp://0.0.0.0:12201
      SEQ_ADDRESS: http://seq:5341

```
