### ISSUE TITLE
All events from Docker Imported as Error Level in Seq

### ISSUE THREAD

**Issue by isaiahlg** [datalust/sqelf#74]
Hi! 

Apologies if this is the wrong forum, let me know if there's a better place to post this. I've set up my organization's instance of Seq to ingest Docker logs from an image of NATS Streaming, but every single event imported shows up as an error:
![image](https://user-images.githubusercontent.com/40040369/87681205-668a4100-c74c-11ea-98f0-12e7d3a541b9.png)

I'm trying to understand the reason for this. The [INF] tag indicates an Information Level, as opposed to [WRN] or [ERR]. What is the logic that this service uses to determine the level of the event? Any help would be much appreciated.

Configurations for Seq and NATS included here...

NATS Configuration:
```YAML
version: '3'
services:
  nats:
    image: nats-streaming:latest
    command: -m 8222 --cluster_id test-cluster --store SQL --sql_driver postgres --sql_source "${connection_string}"
    container_name: Nats
    ports:
      - "4222:4222"
      - "8222:8222"
    network_mode: host
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    restart: always
```

Seq:

```YAML
version: '2'

services:
  seq:
    image: datalust/seq:latest
    container_name: Seq_Server
    volumes:
      - seq:/data
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    mem_limit: 3g
    memswap_limit: 3g
    restart: always

  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    ports:
      - "12201:12201/udp"
    network_mode: host
    environment:
      SEQ_ADDRESS: "http://localhost:5341"
      restart: unless-stopped
    depends_on:
      - seq

volumes:
  seq:
```

**Comment by nblumhardt** [comment]
Hi Isaiah, thanks for dropping by! We'll dig into this and let you know what we find 👍

**Comment by KodrAus** [comment]
Hi @isaiahlg :wave:

The server uses the GELF messages level property to determine what level to forward the event as and doesn't consider any content in the message itself. The level property should follow the standard syslog integer values, with `1` being alert, `3` being error, and `6` being info. I have noticed some logging frameworks give different meanings to these numbers though (I think it was `fluentd` I was looking at, which is Ruby).

I've merged #75, which is published on Docker Hub under the image `datalust/sqelf-ci:2.0.290-dev`. Is it possible to update your `seq-input-gelf` compose to something like:

```yaml
 seq-input-gelf:
    image: datalust/sqelf-ci:2.0.290-dev
    ports:
      - "12201:12201/udp"
    network_mode: host
    environment:
      SEQ_ADDRESS: "http://localhost:5341"
      GELF_ENABLE_DIAGNOSTICS="True"
      restart: unless-stopped
    depends_on:
      - seq
```

Then, when events are logged in Seq you should see an extra `raw_payload` property attached that should give a clue of what level the message is being sent with.
